### ISSUE TITLE
Provide JSONs via $httpBackend

### ISSUE THREAD

**Issue by gustavohenke** [EE/karma-ng-json2js-preprocessor#10]
Hey,
It would be awesome if this plugin could provide the JSON files via `$httpBackend` backend definitions:

```js
$httpBackend.whenGET('my.json').respond(...)
```

Thanks in advance!

**Comment by mzgol** [comment]
I'm not sure what exactly you're asking for... This should work:
```js
describe('tests', function(){
    beforeEach(module('data/my-file.json'));
    beforeEach(inject(function ($httpBackend , dataMyFile) {
        $httpBackend.whenGET('data/my-file.json').respond(200, dataMyFile);
    }));
    it('should not fail', function() {/* code */});
});
```

**Comment by gustavohenke** [comment]
Yeah, that works, but it's somewhat verbose IMO.
I was initially downloading the JSONs via app production code, but I refactored my app to use constants (I feel so dumb I haven't thought of using them before).

So, it's up to you to decide if this is useful in the scope of this plugin :)

**Comment by mzgol** [comment]
What's your full proposal? How would that work?

-- 
Michał Gołębiowski

**Comment by gustavohenke** [comment]
The plugin would provide `data/my.json` contents as an `$httpBackend` mocked response, so the production code makes use of the same JSON contents in the tests.

For example:
My app needs i18n. There's an filter which will format phone numbers based in the mask defined in the i18n files. I wanted to use those masks in the tests because they're somewhat complex.

As I said, my app used to download those JSON files based in the picked language/culture, but I revamped my build process. Now I no longer use `.json`s, because after seeing this plugin I realized I could use constants :)

So, if you decide this is useful, great, but I won't be able to help test it anymore :cry:

**Comment by mzgol** [comment]
OK, I understand. The problem is to do that I need to inject `$httpBackend` after loading `angular-mocks` as otherwise it doesn't have these all helper methods. Also, all injecting needs to happen after all `beforeEach(module(sth))` but my preprocessor will process all mocks before those invocations... So IMO it's impossible to achieve what you want using just a preprocessor.

**Comment by gustavohenke** [comment]
> Also, all injecting needs to happen after all beforeEach(module(sth))

True, but you could export a new module with a run block.

Anyway, I'm closing.

**Comment by mzgol** [comment]
> True, but you could export a new module with a run block.

I need the `$httpBackend` from `angular-mocks` and here I'd get the one from regular Angular that doesn't work, so this would require to load the JSON files after `angular-mocks`. Also, not all people will want this auto-loading to work so this would need to be a config option, not sure if that's possible with a Karma preprocessor.
